#!/bin/bash
set -e

# setup은 마지막에 실행됨
function setup {
    setupGit
    setupUserrc
}

function appendIfNotExist {
	grep -q "$1" $2 || echo "$1" >> $2
}

function setupGit {
    git config --global user.email "kybinz@gmail.com"
    git config --global user.name "kim yongbin"
}


function setupUserrc {
    if [ -e $HOME/.userrc ]; then
        echo "'$HOME/.userrc' exists. skip'"
        return
    fi

    cat > $HOME/.userrc << EOF
# ps1
parse_git_branch() {
    git branch 2> /dev/null | sed -e '/^[^*]/d' -e 's/* \(.*\)/ (\1)/'
}
export PS1="\u@\h \[\033[32m\]\w\[\033[33m\]\$(parse_git_branch)\[\033[00m\] $ "

# editor
export EDITOR=tor

# jd
function jd {
    cd -P "$HOME/.jd/$1"
}
function _jd {
    COMPREPLY=()
    if [ -d $HOME/.jd ]; then
        local dirs=`ls $HOME/.jd`
        local cur="${COMP_WORDS[COMP_CWORD]}"
        COMPREPLY=($(compgen -W "$dirs" -- $cur))
        return 0
    fi
}
complete -F _jd jd

# go
export GOPATH=$HOME
export PATH=$GOPATH/bin:$PATH

# keep
export KEEP_GITHUB_USER=
export KEEP_GITHUB_AUTH=
EOF

    mkdir -p $HOME/.jd
    appendIfNotExist 'source $HOME/.userrc' $HOME/.bashrc
    echo "run 'source $HOME/.userrc' to get user environment now."
}

setup
