#!/bin/bash
set -e

# setup은 마지막에 실행됨
function setup {
    if [ ! "$(id -u)" -eq 0 ]; then
        echo "please run as root"
        return
    fi

    setupGo
    setupTor
    setupKeep
    setupRipgrep

    # 이 시스템의 각 유저들이 따로 이 레포지터리를 클론하지 않게 함
    cp $(dirname ${BASH_SOURCE})/setup-user /usr/local/bin
    # 사용자 셑업 겸 복사가 잘 되었는지 검사
    setup-user
}

function appendIfNotExist {
	grep -q "$1" $2 || echo "$1" >> $2
}

function hasCmd {
    command -v $1 >/dev/null 2>&1
    if [ $? = 0 ]; then
        echo "1"
        return 1
    fi
    echo "0"
    return 0
}

function setupGo {
    echo "setting up go"
    if [ -d /usr/local/go ]; then
        echo "'/usr/local/go' exists. skip."
        return
    fi

    GO=go1.13.7

    wget -nc -q https://dl.google.com/go/$GO.linux-amd64.tar.gz
    tar -C /usr/local -zxf $GO.linux-amd64.tar.gz
    rm $GO.linux-amd64.tar.gz
    touch /etc/profile.d/go.sh
    appendIfNotExist 'export PATH=/usr/local/go/bin:$PATH' /etc/profile.d/go.sh
    source /etc/profile.d/go.sh
}

function setupTor {
    echo "setting up tor"
    if [ $(hasCmd tor) = "1" ]; then
        echo "'tor' exist. skip."
        return
    fi
    git clone https://github.com/kybin/tor
    cd tor
    go build -o /usr/local/bin
    cd $OLDPWD
    rm -rf tor
}

function setupKeep {
    echo "setting up keep"
    if [ $(hasCmd keep) = "1" ]; then
        echo "'keep' exist. skip."
        return
    fi
    git clone https://github.com/lazypic/keep
    cd keep
    go build -o /usr/local/bin
    cd $OLDPWD
    rm -rf keep
}

function setupRipgrep {
    echo "setting up rg"
    if [ $(hasCmd rg) = "1" ]; then
        echo "'rg' exist. skip."
        return
    fi
    wget -nc -q https://github.com/BurntSushi/ripgrep/releases/download/11.0.2/ripgrep-11.0.2-i686-unknown-linux-musl.tar.gz
    tar -zxf ripgrep-11.0.2-i686-unknown-linux-musl.tar.gz ripgrep-11.0.2-i686-unknown-linux-musl/rg
    mv ripgrep-11.0.2-i686-unknown-linux-musl/rg /usr/local/bin
    rm -r ripgrep-11.0.2-i686-unknown-linux-musl
    rm ripgrep-11.0.2-i686-unknown-linux-musl.tar.gz
}

setup
