#!/bin/bash

# setup은 마지막에 실행됨
function setup {
    setupGit
    setupUserrc
}

function appendIfNotExist {
	grep -q "$1" $2 || echo "$1" >> $2
}

function setupGit {
    git config --global user.email "kybinz@gmail.com"
    git config --global user.name "kim yongbin"
}

function setupUserrc {
    if [ -e $HOME/.userrc ]; then
        echo "'$HOME/.userrc' exists. skip'"
        appendIfNotExist 'source $HOME/.userrc' $HOME/.bashrc
    fi
    cp $(dirname ${BASH_SOURCE})/userrc $HOME/.userrc
    source $HOME/.userrc
}

setup
