#!/bin/bash
set -e

# setup은 마지막에 실행됨
function setup {
    setupGit
    setupUserrc
}

function appendIfNotExist {
	grep -q "$1" $2 || echo "$1" >> $2
}

function setupGit {
    git config --global user.email "kybinz@gmail.com"
    git config --global user.name "kim yongbin"
}


function setupUserrc {
    if [ -e $HOME/.userrc ]; then
        echo "'$HOME/.userrc' exists. skip'"
    fi

    cat > $HOME/.userrc << EOF
# ps1
parse_git_branch() {
    git branch 2> /dev/null | sed -e '/^[^*]/d' -e 's/* \(.*\)/ (\1)/'
}
export PS1="\u@\h \[\033[32m\]\w\[\033[33m\]\$(parse_git_branch)\[\033[00m\] $ "

# editor
export EDITOR=tor

# go
export GOPATH=$HOME
export PATH=$GOPATH/bin:$PATH

# keep
export KEEP_GITHUB_USER=
export KEEP_GITHUB_AUTH=
EOF

    appendIfNotExist 'source $HOME/.userrc' $HOME/.bashrc
    echo "run 'source $HOME/.userrc' to get user environment now."
}

setup
